const catalogBooks = [
	{ title: 'Nhà giả kim', author: 'Paulo Coelho', price: 89000, category: 'van-hoc', cover: 'cover-1', label: 'THE\nALCHEMIST', image: 'https://covers.openlibrary.org/b/id/14846382-L.jpg?default=false' },
	{ title: 'Đi tìm lẽ sống', author: 'Viktor E. Frankl', price: 99000, category: 'ky-nang', cover: 'cover-2', label: 'MAN’S\nSEARCH' },
	{ title: 'Tư duy nhanh và chậm', author: 'Daniel Kahneman', price: 159000, category: 'kinh-te', cover: 'cover-3', label: 'THINKING\nFAST & SLOW', image: 'https://covers.openlibrary.org/b/id/13290711-L.jpg?default=false' },
	{ title: 'Tuổi trẻ đáng giá bao nhiêu?', author: 'Rosie Nguyễn', price: 89000, category: 'ky-nang', cover: 'cover-4', label: 'TUỔI TRẺ\nĐÁNG GIÁ?' },
	{ title: 'Mắt biếc', author: 'Nguyễn Nhật Ánh', price: 99000, category: 'van-hoc', cover: 'cover-5', label: 'MẮT\nBIẾC', image: 'https://covers.openlibrary.org/b/id/13258074-L.jpg?default=false' },
	{ title: 'Đắc nhân tâm', author: 'Dale Carnegie', price: 98000, category: 'ky-nang', cover: 'cover-2', label: 'ĐẮC NHÂN\nTÂM', image: 'https://covers.openlibrary.org/b/id/13314878-L.jpg?default=false' },
	{ title: 'Sapiens: Lược sử loài người', author: 'Yuval Noah Harari', price: 189000, category: 'kinh-te', cover: 'cover-3', label: 'SAPIENS', image: 'https://covers.openlibrary.org/b/id/8634250-L.jpg?default=false' },
	{ title: 'Dám bị ghét', author: 'Ichiro Kishimi, Fumitake Koga', price: 109000, category: 'ky-nang', cover: 'cover-4', label: 'DÁM BỊ GHÉT' },
	{ title: 'Người giàu có nhất thành Babylon', author: 'George S. Clason', price: 89000, category: 'kinh-te', cover: 'cover-1', label: 'NGƯỜI GIÀU\nBABYLON', image: 'https://covers.openlibrary.org/b/id/10491331-L.jpg?default=false' },
	{ title: 'Bố già', author: 'Mario Puzo', price: 159000, category: 'van-hoc', cover: 'cover-5', label: 'BỐ GIÀ', image: 'https://covers.openlibrary.org/b/id/6507069-L.jpg?default=false' },
	{ title: 'Cà phê cùng Tony', author: 'Tony Buổi Sáng', price: 90000, category: 'ky-nang', cover: 'cover-2', label: 'CÀ PHÊ\nCÙNG TONY', image: 'https://covers.openlibrary.org/b/id/9175811-L.jpg?default=false' },
	{ title: 'Nghĩ giàu và làm giàu', author: 'Napoleon Hill', price: 115000, category: 'kinh-te', cover: 'cover-3', label: 'NGHĨ GIÀU\nLÀM GIÀU', image: 'https://covers.openlibrary.org/b/id/14542536-L.jpg?default=false' },
	{ title: 'Hành trình về phương Đông', author: 'Baird T. Spalding', price: 99000, category: 'van-hoc', cover: 'cover-4', label: 'HÀNH TRÌNH\nPHƯƠNG ĐÔNG', image: 'https://covers.openlibrary.org/b/id/1626611-L.jpg?default=false' },
	{ title: 'Cho tôi xin một vé đi tuổi thơ', author: 'Nguyễn Nhật Ánh', price: 85000, category: 'van-hoc', cover: 'cover-5', label: 'VÉ ĐI\nTUỔI THƠ' },
	{ title: 'Không gia đình', author: 'Hector Malot', price: 145000, category: 'van-hoc', cover: 'cover-1', label: 'KHÔNG\nGIA ĐÌNH', image: 'https://covers.openlibrary.org/b/id/5754078-L.jpg?default=false' },
	{ title: 'Lược sử thời gian', author: 'Stephen Hawking', price: 165000, category: 'khoa-hoc', cover: 'cover-2', label: 'LƯỢC SỬ\nTHỜI GIAN' },
	{ title: 'Vũ trụ', author: 'Carl Sagan', price: 189000, category: 'khoa-hoc', cover: 'cover-3', label: 'VŨ TRỤ' },
	{ title: 'Súng, vi trùng và thép', author: 'Jared Diamond', price: 215000, category: 'lich-su', cover: 'cover-4', label: 'SÚNG, VI TRÙNG\nVÀ THÉP' },
	{ title: 'Việt Nam sử lược', author: 'Trần Trọng Kim', price: 175000, category: 'lich-su', cover: 'cover-5', label: 'VIỆT NAM\nSỬ LƯỢC' },
	{ title: 'Harry Potter và Hòn đá Phù thủy', author: 'J. K. Rowling', price: 120000, category: 'thieu-nhi', cover: 'cover-1', label: 'HARRY\nPOTTER' },
	{ title: 'Dế mèn phiêu lưu ký', author: 'Tô Hoài', price: 78000, category: 'thieu-nhi', cover: 'cover-2', label: 'DẾ MÈN\nPHIÊU LƯU KÝ' },
	{ title: 'Sherlock Holmes toàn tập', author: 'Arthur Conan Doyle', price: 249000, category: 'trinh-tham', cover: 'cover-3', label: 'SHERLOCK\nHOLMES' },
	{ title: 'Án mạng trên chuyến tàu tốc hành Phương Đông', author: 'Agatha Christie', price: 135000, category: 'trinh-tham', cover: 'cover-4', label: 'ÁN MẠNG\nPHƯƠNG ĐÔNG' },
	{ title: 'Tâm lý học đám đông', author: 'Gustave Le Bon', price: 99000, category: 'tam-ly', cover: 'cover-5', label: 'TÂM LÝ HỌC\nĐÁM ĐÔNG' },
	{ title: 'Bắt trẻ đồng xanh', author: 'J. D. Salinger', price: 118000, category: 'tam-ly', cover: 'cover-1', label: 'BẮT TRẺ\nĐỒNG XANH' },
	{ title: 'Clean Code', author: 'Robert C. Martin', price: 320000, category: 'cong-nghe', cover: 'cover-2', label: 'CLEAN\nCODE' },
	{ title: 'Design Patterns', author: 'Erich Gamma và cộng sự', price: 350000, category: 'cong-nghe', cover: 'cover-3', label: 'DESIGN\nPATTERNS' },
	{ title: 'English Grammar in Use', author: 'Raymond Murphy', price: 210000, category: 'ngoai-ngu', cover: 'cover-4', label: 'ENGLISH\nGRAMMAR' },
	{ title: 'Từ điển Anh - Việt', author: 'Nhiều tác giả', price: 145000, category: 'ngoai-ngu', cover: 'cover-5', label: 'ANH - VIỆT' },
	{ title: 'Những người khốn khổ', author: 'Victor Hugo', price: 198000, category: 'van-hoc', cover: 'cover-1', label: 'NHỮNG NGƯỜI\nKHỐN KHỔ' },
	{ title: 'Thằng gù Nhà thờ Đức Bà', author: 'Victor Hugo', price: 155000, category: 'van-hoc', cover: 'cover-2', label: 'NHÀ THỜ\nĐỨC BÀ' },
	{ title: '7 thói quen hiệu quả', author: 'Stephen R. Covey', price: 175000, category: 'ky-nang', cover: 'cover-3', label: '7 THÓI QUEN\nHIỆU QUẢ' },
	{ title: 'Atomic Habits', author: 'James Clear', price: 189000, category: 'ky-nang', cover: 'cover-4', label: 'ATOMIC\nHABITS' },
	{ title: 'Nghệ thuật tinh tế của việc đếch quan tâm', author: 'Mark Manson', price: 149000, category: 'ky-nang', cover: 'cover-5', label: 'NGHỆ THUẬT\nTINH TẾ' },
	{ title: 'Cha giàu cha nghèo', author: 'Robert Kiyosaki', price: 169000, category: 'kinh-te', cover: 'cover-1', label: 'CHA GIÀU\nCHA NGHÈO' },
	{ title: 'Nhà đầu tư thông minh', author: 'Benjamin Graham', price: 250000, category: 'kinh-te', cover: 'cover-2', label: 'NHÀ ĐẦU TƯ\nTHÔNG MINH' },
	{ title: 'Quốc gia khởi nghiệp', author: 'Dan Senor, Saul Singer', price: 135000, category: 'kinh-te', cover: 'cover-3', label: 'QUỐC GIA\nKHỞI NGHIỆP' },
	{ title: 'Kinh tế học hài hước', author: 'Steven D. Levitt', price: 125000, category: 'kinh-te', cover: 'cover-4', label: 'KINH TẾ HỌC\nHÀI HƯỚC' },
	{ title: 'Gen: Lịch sử tự nhiên của sự sống', author: 'Siddhartha Mukherjee', price: 245000, category: 'khoa-hoc', cover: 'cover-5', label: 'GEN\nSỰ SỐNG' },
	{ title: 'Lược sử vạn vật', author: 'Bill Bryson', price: 210000, category: 'khoa-hoc', cover: 'cover-1', label: 'LƯỢC SỬ\nVẠN VẬT' },
	{ title: 'Vật lý của những điều tưởng chừng không thể', author: 'Michio Kaku', price: 195000, category: 'khoa-hoc', cover: 'cover-2', label: 'VẬT LÝ\nKỲ DIỆU' },
	{ title: 'Toán học vui', author: 'Martin Gardner', price: 145000, category: 'khoa-hoc', cover: 'cover-3', label: 'TOÁN HỌC\nVUI' },
	{ title: 'Câu chuyện khoa học', author: 'Nhiều tác giả', price: 130000, category: 'khoa-hoc', cover: 'cover-4', label: 'CÂU CHUYỆN\nKHOA HỌC' },
	{ title: 'Homo Deus', author: 'Yuval Noah Harari', price: 225000, category: 'khoa-hoc', cover: 'cover-5', label: 'HOMO\nDEUS' },
	{ title: 'Đại Việt sử ký toàn thư', author: 'Nhiều tác giả', price: 280000, category: 'lich-su', cover: 'cover-1', label: 'ĐẠI VIỆT\nSỬ KÝ' },
	{ title: 'Lịch sử thế giới', author: 'E. H. Gombrich', price: 220000, category: 'lich-su', cover: 'cover-2', label: 'LỊCH SỬ\nTHẾ GIỚI' },
	{ title: 'Chiến tranh và hòa bình', author: 'Lev Tolstoy', price: 260000, category: 'lich-su', cover: 'cover-3', label: 'CHIẾN TRANH\nVÀ HÒA BÌNH' },
	{ title: 'Winston Churchill: Tiểu sử', author: 'Andrew Roberts', price: 245000, category: 'lich-su', cover: 'cover-4', label: 'WINSTON\nCHURCHILL' },
	{ title: 'Cổ sử Trung Hoa', author: 'Ngô Sĩ Liên', price: 180000, category: 'lich-su', cover: 'cover-5', label: 'CỔ SỬ\nTRUNG HOA' },
	{ title: 'Lịch sử Việt Nam bằng tranh', author: 'Nhiều tác giả', price: 115000, category: 'lich-su', cover: 'cover-1', label: 'LỊCH SỬ\nVIỆT NAM' },
	{ title: 'Hoàng tử bé', author: 'Antoine de Saint-Exupéry', price: 69000, category: 'thieu-nhi', cover: 'cover-2', label: 'HOÀNG\nTỬ BÉ' },
	{ title: 'Alice ở xứ sở diệu kỳ', author: 'Lewis Carroll', price: 85000, category: 'thieu-nhi', cover: 'cover-3', label: 'ALICE\nDIỆU KỲ' },
	{ title: 'Winnie-the-Pooh', author: 'A. A. Milne', price: 95000, category: 'thieu-nhi', cover: 'cover-4', label: 'WINNIE\nTHE POOH' },
	{ title: 'Nghìn lẻ một đêm', author: 'Nhiều tác giả', price: 125000, category: 'thieu-nhi', cover: 'cover-5', label: 'NGHÌN LẺ\nMỘT ĐÊM' },
	{ title: 'Kính vạn hoa', author: 'Nguyễn Nhật Ánh', price: 88000, category: 'thieu-nhi', cover: 'cover-1', label: 'KÍNH\nVẠN HOA' },
	{ title: 'Chuyện con mèo dạy hải âu bay', author: 'Luis Sepúlveda', price: 78000, category: 'thieu-nhi', cover: 'cover-2', label: 'MÈO DẠY\nHẢI ÂU' },
	{ title: 'Mật mã Da Vinci', author: 'Dan Brown', price: 159000, category: 'trinh-tham', cover: 'cover-3', label: 'MẬT MÃ\nDA VINCI' },
	{ title: 'Cô gái có hình xăm rồng', author: 'Stieg Larsson', price: 169000, category: 'trinh-tham', cover: 'cover-4', label: 'HÌNH XĂM\nRỒNG' },
	{ title: 'Mười người da đen', author: 'Agatha Christie', price: 119000, category: 'trinh-tham', cover: 'cover-5', label: 'MƯỜI NGƯỜI\nDA ĐEN' },
	{ title: 'Người gác đêm', author: 'Jeffery Deaver', price: 139000, category: 'trinh-tham', cover: 'cover-1', label: 'NGƯỜI\nGÁC ĐÊM' },
	{ title: 'Phía sau nghi can X', author: 'Higashino Keigo', price: 125000, category: 'trinh-tham', cover: 'cover-2', label: 'NGHI CAN X' },
	{ title: 'Sự im lặng của bầy cừu', author: 'Thomas Harris', price: 149000, category: 'trinh-tham', cover: 'cover-3', label: 'SỰ IM LẶNG\nBẦY CỪU' },
	{ title: 'Trí tuệ xúc cảm', author: 'Daniel Goleman', price: 185000, category: 'tam-ly', cover: 'cover-4', label: 'TRÍ TUỆ\nXÚC CẢM' },
	{ title: 'Im lặng: Sức mạnh của người hướng nội', author: 'Susan Cain', price: 155000, category: 'tam-ly', cover: 'cover-5', label: 'SỨC MẠNH\nHƯỚNG NỘI' },
	{ title: 'Tư duy tích cực', author: 'Norman Vincent Peale', price: 99000, category: 'tam-ly', cover: 'cover-1', label: 'TƯ DUY\nTÍCH CỰC' },
	{ title: 'Nghệ thuật yêu', author: 'Erich Fromm', price: 110000, category: 'tam-ly', cover: 'cover-2', label: 'NGHỆ THUẬT\nYÊU' },
	{ title: 'Cạm bẫy của tâm trí', author: 'Daniel Kahneman', price: 145000, category: 'tam-ly', cover: 'cover-3', label: 'CẠM BẪY\nTÂM TRÍ' },
	{ title: 'Tâm lý học tiền', author: 'Morgan Housel', price: 175000, category: 'tam-ly', cover: 'cover-4', label: 'TÂM LÝ\nTIỀN' },
	{ title: 'The Pragmatic Programmer', author: 'David Thomas, Andrew Hunt', price: 330000, category: 'cong-nghe', cover: 'cover-5', label: 'PRAGMATIC\nPROGRAMMER' },
	{ title: 'JavaScript hiện đại', author: 'Marijn Haverbeke', price: 290000, category: 'cong-nghe', cover: 'cover-1', label: 'JAVASCRIPT\nHIỆN ĐẠI' },
	{ title: 'Eloquent JavaScript', author: 'Marijn Haverbeke', price: 275000, category: 'cong-nghe', cover: 'cover-2', label: 'ELOQUENT\nJAVASCRIPT' },
	{ title: 'You Don\'t Know JS', author: 'Kyle Simpson', price: 285000, category: 'cong-nghe', cover: 'cover-3', label: 'YOU DON\'T\nKNOW JS' },
	{ title: 'AI 2041', author: 'Kai-Fu Lee, Chen Qiufan', price: 220000, category: 'cong-nghe', cover: 'cover-4', label: 'AI\n2041' },
	{ title: 'Học máy cơ bản', author: 'Nhiều tác giả', price: 245000, category: 'cong-nghe', cover: 'cover-5', label: 'HỌC MÁY\nCƠ BẢN' },
	{ title: 'Oxford Word Skills', author: 'Ruth Gairns, Stuart Redman', price: 185000, category: 'ngoai-ngu', cover: 'cover-1', label: 'OXFORD\nWORD SKILLS' },
	{ title: 'Tự học TOEIC', author: 'Nhiều tác giả', price: 145000, category: 'ngoai-ngu', cover: 'cover-2', label: 'TỰ HỌC\nTOEIC' },
	{ title: 'IELTS Practice Tests', author: 'Nhiều tác giả', price: 195000, category: 'ngoai-ngu', cover: 'cover-3', label: 'IELTS\nPRACTICE' },
	{ title: 'Tự học tiếng Nhật', author: 'Nhiều tác giả', price: 155000, category: 'ngoai-ngu', cover: 'cover-4', label: 'TIẾNG\nNHẬT' },
	{ title: 'Giáo trình tiếng Trung', author: 'Nhiều tác giả', price: 165000, category: 'ngoai-ngu', cover: 'cover-5', label: 'TIẾNG\nTRUNG' },
	{ title: 'Tiếng Hàn sơ cấp', author: 'Nhiều tác giả', price: 150000, category: 'ngoai-ngu', cover: 'cover-1', label: 'TIẾNG\nHÀN' }
];

if (typeof module !== 'undefined' && module.exports) {
	module.exports = catalogBooks;
} else {
	globalThis.BOOKNEST_BOOKS = catalogBooks;
}
